sudo: required

arch:
  - arm64
os: linux

language: generic

git:
  depth: false

dist: xenial

cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - docker pull moussavdb/build-graalvm-arm64

script:
  - git clone https://$GH_TOKEN@github.com/$REPO_OWNER_NAME/$TRAVIS_BRANCH
  - travis_retry docker run -v $TRAVIS_BRANCH:$TRAVIS_BRANCH -v $HOME/.m2:/root/.m2 moussavdb/build-graalvm-arm64 mvn -f $TRAVIS_BRANCH/pom.xml package
