sudo: required

language: generic

git:
  depth: false

dist: xenial

cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - docker pull moussavdb/build-graalvm-arm64

script:
  - git clone https://$GH_TOKEN@github.com/$REPO_OWNER_NAME/$TRAVIS_BRANCH
  - travis_retry docker run -v $PWD:/src -v $HOME/.m2:/root/.m2 moussavdb/build-graalvm-arm64 mvn package
